package Parser.Error;

public enum ErrorTypes {
    MISSING_SEMICOLON,
    MISSING_DATA_TYPE,
    MISSING_EXPRESSION,
    MISSING_PARENTHESES,
    MISSING_IDENTIFIER,
    MISSING_ASSIGNMENT,
    MISSING_SQUARE_BRACKETS,
    MISSING_NUMERAL_EXPRESSION,
    INVALID_DATA_TYPE,
    NOT_SUPPORTED_DATA_TYPE,
    FUNCTION_DECLARATION_NOT_ALLOWED,
    UNEXPECTED_ERROR,
    MISSING_COLON,
    VARIABLE_DECLARATION_ERROR,
    FUNCTION_DECLARATION_ERROR,
    CASE_ERROR,
    MISSING_SEPARATOR,
    INCOMPLETE_EXPRESSION,
    DOUBLE_ELSE
}
