package Parser.Error;

public enum ErrorTypes {
    MISSING_SEMICOLON,
    MISSING_DATA_TYPE,
    MISSING_EXPRESSION,
    MISSING_PARENTHESES,
    MISSING_IDENTIFIER,
    MISSING_ASSIGNMENT,
    MISSING_SQUARE_BRACKETS,
    MISSING_NUMERAL_EXPRESSION,
    INVALID_DATA_TYPE,
    MISSING_BRACKETS
}
