package Parser.Error;

public enum ErrorTypes {
    MISSING_SEMICOLON,
    MISSING_DATA_TYPE,
    MISSING_EXPRESSION,
    MISSING_PARENTHESES,
    MISSING_VARIABLE,
    MISSING_ASSIGNMENT,
    MISSING_SQUARE_BRACKETS,


}
