
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 25 17:44:54 CST 2021
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 66;
  public static final int OPERATOR_CONTINUE_LINE = 47;
  public static final int IDENTIFIER = 2;
  public static final int OPERATOR_DIVIDE_EQ = 37;
  public static final int READ = 70;
  public static final int CONST = 56;
  public static final int OPERATOR_BITWISE_AND = 48;
  public static final int CHARACTER_ERROR = 6;
  public static final int OPERATOR_MULTIPLY_EQ = 46;
  public static final int OPERATOR_R_SHIFT_EQ = 41;
  public static final int ASSIGNMENT = 52;
  public static final int OPERATOR_DIVIDE = 27;
  public static final int OPERATOR_SQ_BRACKET = 43;
  public static final int COMMENTS_ERROR = 5;
  public static final int OPERATOR_COMPARATIVE = 50;
  public static final int OPERATOR_BOOLEAN = 30;
  public static final int RESERVED_WORDS = 11;
  public static final int OPERATOR_BRACKET = 29;
  public static final int OPERATOR_REMAINDER = 38;
  public static final int OPERATOR_PARENTHESIS_R = 45;
  public static final int OPERATOR_PARENTHESIS_L = 44;
  public static final int LITERAL_EXPONENTIAL_FLOAT = 21;
  public static final int LITERAL_STRING = 18;
  public static final int OPERATOR_NOT = 51;
  public static final int OPERATOR_DEC = 23;
  public static final int RESERVED_DATA_TYPE = 14;
  public static final int LITERAL_DECIMAL = 19;
  public static final int LITERAL_HEXA = 15;
  public static final int WRITE = 71;
  public static final int LONG = 64;
  public static final int OPERATOR_MULTIPLY = 36;
  public static final int STRING_ERROR = 3;
  public static final int WHILE = 69;
  public static final int CHAR = 55;
  public static final int IDENTIFIER_ERROR = 7;
  public static final int OPERATOR_BINARY = 28;
  public static final int OPERATOR_MEMORY = 26;
  public static final int SWITCH = 67;
  public static final int DO = 59;
  public static final int FOR = 61;
  public static final int UNKNOWN_ERROR = 4;
  public static final int VOID = 68;
  public static final int RETURN = 65;
  public static final int ELSE = 60;
  public static final int BREAK = 53;
  public static final int INT = 63;
  public static final int OPERATOR_NEGATIVE = 34;
  public static final int OPERATOR_ADD = 24;
  public static final int EOF = 0;
  public static final int DEFAULT = 58;
  public static final int OPERATOR_DOT = 25;
  public static final int OPERATOR_BITWISE_EXCLUSIVE_OR = 49;
  public static final int FLOAT_MANY_DOTS_ERROR = 8;
  public static final int OPERATOR_BITWISE_OR = 42;
  public static final int OPERATOR_ASSIGNMENT = 39;
  public static final int RESERVED_MODIFIER = 12;
  public static final int OPERATOR_MINUS_EQ = 32;
  public static final int RESERVED_CONDITION = 13;
  public static final int error = 1;
  public static final int OPERATOR_INC = 22;
  public static final int CONTINUE = 57;
  public static final int IF = 62;
  public static final int RESERVED_ENUM = 10;
  public static final int OPERATOR_PLUS_EQ = 31;
  public static final int OPERATOR_END_LINE = 33;
  public static final int LITERAL_CHARACTER = 20;
  public static final int CASE = 54;
  public static final int OPERATOR_SEPARATE = 35;
  public static final int LITERAL_OCTAL = 17;
  public static final int RESERVED_LOOP = 9;
  public static final int OPERATOR_L_SHIFT_EQ = 40;
  public static final int LITERAL_FLOAT = 16;
}

