
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERATOR_COMPARATIVE = 28;
  public static final int SHORT = 42;
  public static final int OPERATOR_BRACKET_L = 15;
  public static final int OPERATOR_COLON = 30;
  public static final int CONST = 34;
  public static final int CHAR = 33;
  public static final int RESERVED_DATA_TYPE = 3;
  public static final int OPERATOR_SEPARATE = 19;
  public static final int CASE = 32;
  public static final int CONTINUE = 35;
  public static final int INT = 49;
  public static final int OPERATOR_END_LINE = 17;
  public static final int LITERAL_EXPONENTIAL_FLOAT = 10;
  public static final int FOR = 39;
  public static final int WRITE = 47;
  public static final int OPERATOR_SQ_BRACKET_R = 25;
  public static final int OPERATOR_DEC = 12;
  public static final int OPERATOR_SQ_BRACKET_L = 24;
  public static final int OPERATOR_ASSIGNMENT_EQUALS = 23;
  public static final int OPERATOR_NEGATIVE = 18;
  public static final int OPERATOR_REMAINDER = 21;
  public static final int LITERAL_DECIMAL = 8;
  public static final int OPERATOR_DIVIDE = 14;
  public static final int OPERATOR_MULTIPLY = 20;
  public static final int OPERATOR_PARENTHESIS_R = 27;
  public static final int IF = 40;
  public static final int LITERAL_CHARACTER = 9;
  public static final int EOF = 0;
  public static final int OPERATOR_PARENTHESIS_L = 26;
  public static final int RETURN = 41;
  public static final int error = 1;
  public static final int BREAK = 31;
  public static final int VOID = 44;
  public static final int LITERAL_FLOAT = 5;
  public static final int LITERAL_HEXA = 4;
  public static final int SWITCH = 43;
  public static final int OPERATOR_NOT = 29;
  public static final int ELSE = 38;
  public static final int READ = 46;
  public static final int LITERAL_STRING = 7;
  public static final int WHILE = 45;
  public static final int IDENTIFIER_ERROR = 2;
  public static final int DEFAULT = 36;
  public static final int OPERATOR_INC = 11;
  public static final int LONG = 50;
  public static final int OPERATOR_ADD = 13;
  public static final int DO = 37;
  public static final int OPERATOR_ASSIGNMENT = 22;
  public static final int LITERAL_OCTAL = 6;
  public static final int IDENTIFIER = 48;
  public static final int OPERATOR_BRACKET_R = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER_ERROR",
  "RESERVED_DATA_TYPE",
  "LITERAL_HEXA",
  "LITERAL_FLOAT",
  "LITERAL_OCTAL",
  "LITERAL_STRING",
  "LITERAL_DECIMAL",
  "LITERAL_CHARACTER",
  "LITERAL_EXPONENTIAL_FLOAT",
  "OPERATOR_INC",
  "OPERATOR_DEC",
  "OPERATOR_ADD",
  "OPERATOR_DIVIDE",
  "OPERATOR_BRACKET_L",
  "OPERATOR_BRACKET_R",
  "OPERATOR_END_LINE",
  "OPERATOR_NEGATIVE",
  "OPERATOR_SEPARATE",
  "OPERATOR_MULTIPLY",
  "OPERATOR_REMAINDER",
  "OPERATOR_ASSIGNMENT",
  "OPERATOR_ASSIGNMENT_EQUALS",
  "OPERATOR_SQ_BRACKET_L",
  "OPERATOR_SQ_BRACKET_R",
  "OPERATOR_PARENTHESIS_L",
  "OPERATOR_PARENTHESIS_R",
  "OPERATOR_COMPARATIVE",
  "OPERATOR_NOT",
  "OPERATOR_COLON",
  "BREAK",
  "CASE",
  "CHAR",
  "CONST",
  "CONTINUE",
  "DEFAULT",
  "DO",
  "ELSE",
  "FOR",
  "IF",
  "RETURN",
  "SHORT",
  "SWITCH",
  "VOID",
  "WHILE",
  "READ",
  "WRITE",
  "IDENTIFIER",
  "INT",
  "LONG"
  };
}

