// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Regex.flex

package Scanner;

import java.util.*;
import Scanner.DataStructure.*;
import Scanner.Constants.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\5\u0100\1\u0200\1\u0300\1\u0100\5\u0400\1\u0500\1\u0600"+
    "\1\u0700\5\u0100\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00"+
    "\1\u0e00\3\u0100\1\u0f00\17\u0100\1\u1000\165\u0100\1\u0600\1\u0100"+
    "\1\u1100\1\u1200\1\u1300\1\u1400\54\u0100\10\u1500\37\u0100\1\u0a00"+
    "\4\u0100\1\u1600\10\u0100\1\u1700\2\u0100\1\u1800\1\u1900\1\u1400"+
    "\1\u0100\1\u0500\1\u0100\1\u1a00\1\u1700\1\u0900\3\u0100\1\u1300"+
    "\1\u1b00\114\u0100\1\u1c00\1\u1300\153\u0100\1\u1d00\11\u0100\1\u1e00"+
    "\1\u1400\6\u0100\1\u1300\u0f16\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\3\3\22\0\1\1\1\4\1\5"+
    "\2\0\1\6\1\7\1\10\2\11\1\12\1\13\1\14"+
    "\1\15\1\0\1\16\12\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\20\1\0\17\25\1\26\12\25\1\27\1\0"+
    "\1\27\1\30\1\31\1\0\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\25\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\25\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\62\1\64\6\0\1\3\32\0\1\1\u01bf\0\12\17"+
    "\206\0\12\17\306\0\12\17\234\0\12\17\166\0\12\17"+
    "\140\0\12\17\166\0\12\17\106\0\12\17\u0116\0\12\17"+
    "\106\0\12\17\346\0\1\1\u015f\0\12\17\46\0\12\17"+
    "\u012c\0\12\17\200\0\12\17\246\0\12\17\6\0\12\17"+
    "\266\0\12\17\126\0\12\17\206\0\12\17\6\0\12\17"+
    "\246\0\13\1\35\0\2\3\5\0\1\1\57\0\1\1"+
    "\240\0\1\1\u01cf\0\12\17\46\0\12\17\306\0\12\17"+
    "\26\0\12\17\126\0\12\17\u0196\0\12\17\6\0\u0100\65"+
    "\240\0\12\17\206\0\12\17\u012c\0\12\17\200\0\12\17"+
    "\74\0\12\17\220\0\12\17\166\0\12\17\146\0\12\17"+
    "\206\0\12\17\106\0\12\17\266\0\12\17\u0164\0\62\17"+
    "\100\0\12\17\266\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[7936];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\1\1\3"+
    "\1\14\1\3\1\15\1\3\1\16\1\17\1\5\1\1"+
    "\17\16\1\20\2\5\1\21\1\0\1\22\1\15\1\0"+
    "\1\23\1\24\1\25\3\0\1\1\1\0\6\16\1\26"+
    "\4\16\1\27\13\16\1\30\2\0\12\16\1\26\1\31"+
    "\17\16\1\2\1\0\5\16\1\32\14\16\1\0\1\33"+
    "\12\16\1\0\2\16\1\34\1\16\1\33\2\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\66\0\154\0\242\0\66\0\330\0\u010e"+
    "\0\66\0\u0144\0\u017a\0\66\0\u01b0\0\u01e6\0\u021c\0\66"+
    "\0\66\0\u0252\0\154\0\u0288\0\u02be\0\66\0\u0144\0\u02f4"+
    "\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4"+
    "\0\u04da\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\66"+
    "\0\u0654\0\66\0\66\0\242\0\242\0\66\0\u068a\0\66"+
    "\0\66\0\66\0\u06c0\0\u06f6\0\u021c\0\u072c\0\u0762\0\u0798"+
    "\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948"+
    "\0\u097e\0\u09b4\0\u02be\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2"+
    "\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\66\0\u0c3c"+
    "\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec"+
    "\0\u0e22\0\u0e58\0\u0e8e\0\u02be\0\u02be\0\u0ec4\0\u0efa\0\u0f30"+
    "\0\u0f66\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0"+
    "\0\u1116\0\u114c\0\u1182\0\u11b8\0\u06c0\0\u11ee\0\u1224\0\u125a"+
    "\0\u1290\0\u12c6\0\u12fc\0\u02be\0\u1332\0\u1368\0\u139e\0\u13d4"+
    "\0\u140a\0\u1440\0\u1476\0\u14ac\0\u14e2\0\u1518\0\u154e\0\u1584"+
    "\0\u15ba\0\u02be\0\u15f0\0\u1626\0\u165c\0\u1692\0\u16c8\0\u16fe"+
    "\0\u1734\0\u176a\0\u17a0\0\u17d6\0\u180c\0\u1842\0\u1878\0\u02be"+
    "\0\u18ae\0\66\0\u18e4\0\u191a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\2\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\25\1\40"+
    "\1\25\1\41\4\25\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\3\25\1\50\1\51\1\52\1\53\111\0\1\20"+
    "\42\0\2\54\2\0\1\54\1\55\57\54\10\0\1\20"+
    "\13\0\1\56\42\0\2\57\2\0\61\57\24\0\1\56"+
    "\55\0\1\60\7\0\1\56\57\0\1\61\5\0\1\56"+
    "\1\62\53\0\1\63\3\0\1\64\4\0\1\56\61\0"+
    "\1\65\5\0\2\66\3\0\30\66\26\0\1\27\1\20"+
    "\65\0\1\20\1\27\60\0\1\25\5\0\2\25\3\0"+
    "\30\25\32\0\1\67\56\0\1\25\5\0\2\25\3\0"+
    "\22\25\1\70\5\25\23\0\1\25\5\0\2\25\3\0"+
    "\17\25\1\71\10\25\23\0\1\25\5\0\2\25\3\0"+
    "\1\72\6\25\1\73\5\25\1\74\12\25\23\0\1\25"+
    "\5\0\2\25\3\0\4\25\1\75\10\25\1\76\12\25"+
    "\23\0\1\25\5\0\2\25\3\0\12\25\1\72\1\25"+
    "\1\77\10\25\1\100\2\25\23\0\1\25\5\0\2\25"+
    "\3\0\12\25\1\101\2\25\1\102\12\25\23\0\1\25"+
    "\5\0\2\25\3\0\15\25\1\70\12\25\23\0\1\25"+
    "\5\0\2\25\3\0\5\25\1\103\6\25\1\104\13\25"+
    "\23\0\1\25\5\0\2\25\3\0\15\25\1\105\12\25"+
    "\23\0\1\25\5\0\2\25\3\0\4\25\1\106\23\25"+
    "\23\0\1\25\5\0\2\25\3\0\7\25\1\107\1\110"+
    "\10\25\1\111\2\25\1\112\3\25\23\0\1\25\5\0"+
    "\2\25\3\0\26\25\1\113\1\25\23\0\1\25\5\0"+
    "\2\25\3\0\14\25\1\114\13\25\23\0\1\25\5\0"+
    "\2\25\3\0\15\25\1\115\12\25\23\0\1\25\5\0"+
    "\2\25\3\0\7\25\1\116\20\25\27\0\1\56\37\0"+
    "\1\20\12\0\1\117\55\0\12\63\1\120\53\63\2\64"+
    "\1\3\1\0\61\64\20\0\1\66\5\0\2\66\3\0"+
    "\30\66\36\0\1\121\52\0\1\25\5\0\2\25\3\0"+
    "\21\25\1\122\6\25\23\0\1\25\5\0\2\25\3\0"+
    "\4\25\1\123\23\25\23\0\1\25\5\0\2\25\3\0"+
    "\20\25\1\124\7\25\23\0\1\25\5\0\2\25\3\0"+
    "\1\125\27\25\23\0\1\25\5\0\2\25\3\0\14\25"+
    "\1\126\13\25\23\0\1\25\5\0\2\25\3\0\5\25"+
    "\1\127\22\25\23\0\1\25\5\0\2\25\3\0\22\25"+
    "\1\130\5\25\23\0\1\25\5\0\2\25\3\0\22\25"+
    "\1\131\5\25\23\0\1\25\5\0\2\25\3\0\21\25"+
    "\1\132\6\25\23\0\1\25\5\0\2\25\3\0\15\25"+
    "\1\133\12\25\23\0\1\25\5\0\2\25\3\0\17\25"+
    "\1\134\10\25\23\0\1\25\5\0\2\25\3\0\21\25"+
    "\1\135\6\25\23\0\1\25\5\0\2\25\3\0\14\25"+
    "\1\136\13\25\23\0\1\25\5\0\2\25\3\0\6\25"+
    "\1\137\12\25\1\140\6\25\23\0\1\25\5\0\2\25"+
    "\3\0\15\25\1\141\12\25\23\0\1\25\5\0\2\25"+
    "\3\0\6\25\1\142\20\25\1\143\23\0\1\25\5\0"+
    "\2\25\3\0\1\144\16\25\1\145\10\25\23\0\1\25"+
    "\5\0\2\25\3\0\10\25\1\146\17\25\23\0\1\25"+
    "\5\0\2\25\3\0\16\25\1\147\11\25\23\0\1\25"+
    "\5\0\2\25\3\0\10\25\1\150\7\25\1\151\7\25"+
    "\23\0\1\25\5\0\2\25\3\0\10\25\1\152\1\25"+
    "\1\153\15\25\23\0\1\25\5\0\2\25\3\0\10\25"+
    "\1\154\17\25\4\0\12\63\1\120\3\63\1\155\47\63"+
    "\34\0\1\156\50\0\1\25\5\0\2\25\3\0\15\25"+
    "\1\103\12\25\23\0\1\25\5\0\2\25\3\0\1\157"+
    "\27\25\23\0\1\25\5\0\2\25\3\0\4\25\1\103"+
    "\23\25\23\0\1\25\5\0\2\25\3\0\17\25\1\135"+
    "\10\25\23\0\1\25\5\0\2\25\3\0\20\25\1\160"+
    "\1\161\6\25\23\0\1\25\5\0\2\25\3\0\1\162"+
    "\27\25\23\0\1\25\5\0\2\25\3\0\1\25\1\163"+
    "\26\25\23\0\1\25\5\0\2\25\3\0\13\25\1\164"+
    "\14\25\23\0\1\25\5\0\2\25\3\0\4\25\1\165"+
    "\23\25\23\0\1\25\5\0\2\25\3\0\1\104\27\25"+
    "\23\0\1\25\5\0\2\25\3\0\6\25\1\135\21\25"+
    "\23\0\1\25\5\0\2\25\3\0\10\25\1\166\17\25"+
    "\23\0\1\25\5\0\2\25\3\0\22\25\1\165\5\25"+
    "\23\0\1\25\5\0\2\25\3\0\17\25\1\104\10\25"+
    "\23\0\1\25\5\0\2\25\3\0\14\25\1\167\13\25"+
    "\23\0\1\25\5\0\2\25\3\0\4\25\1\170\23\25"+
    "\23\0\1\25\5\0\2\25\3\0\21\25\1\171\6\25"+
    "\23\0\1\25\5\0\2\25\3\0\22\25\1\172\5\25"+
    "\23\0\1\25\5\0\2\25\3\0\21\25\1\173\6\25"+
    "\23\0\1\25\5\0\2\25\3\0\4\25\1\174\23\25"+
    "\23\0\1\25\5\0\2\25\3\0\15\25\1\175\12\25"+
    "\23\0\1\25\5\0\2\25\3\0\10\25\1\176\17\25"+
    "\23\0\1\25\5\0\2\25\3\0\3\25\1\135\24\25"+
    "\23\0\1\25\5\0\2\25\3\0\1\177\27\25\23\0"+
    "\1\25\5\0\2\25\3\0\12\25\1\200\15\25\47\0"+
    "\1\201\41\0\1\25\5\0\2\25\3\0\11\25\1\134"+
    "\16\25\23\0\1\25\5\0\2\25\3\0\21\25\1\202"+
    "\6\25\23\0\1\25\5\0\2\25\3\0\10\25\1\203"+
    "\17\25\23\0\1\25\5\0\2\25\3\0\22\25\1\204"+
    "\5\25\23\0\1\25\5\0\2\25\3\0\12\25\1\205"+
    "\15\25\23\0\1\25\5\0\2\25\3\0\17\25\1\175"+
    "\10\25\23\0\1\25\5\0\2\25\3\0\20\25\1\206"+
    "\7\25\23\0\1\25\5\0\2\25\3\0\4\25\1\207"+
    "\23\25\23\0\1\25\5\0\2\25\3\0\15\25\1\210"+
    "\12\25\23\0\1\25\5\0\2\25\3\0\10\25\1\211"+
    "\17\25\23\0\1\25\5\0\2\25\3\0\2\25\1\160"+
    "\25\25\23\0\1\25\5\0\2\25\3\0\2\25\1\212"+
    "\25\25\23\0\1\25\5\0\2\25\3\0\3\25\1\213"+
    "\24\25\23\0\1\25\5\0\2\25\3\0\14\25\1\202"+
    "\13\25\23\0\1\25\5\0\2\25\3\0\6\25\1\142"+
    "\21\25\23\0\1\25\5\0\2\25\3\0\21\25\1\214"+
    "\6\25\23\0\1\25\5\0\2\25\3\0\4\25\1\134"+
    "\23\25\42\0\1\215\46\0\1\25\5\0\2\25\3\0"+
    "\14\25\1\216\13\25\23\0\1\25\5\0\2\25\3\0"+
    "\12\25\1\160\15\25\23\0\1\25\5\0\2\25\3\0"+
    "\4\25\1\135\23\25\23\0\1\25\5\0\2\25\3\0"+
    "\21\25\1\217\6\25\23\0\1\25\5\0\2\25\3\0"+
    "\3\25\1\220\24\25\23\0\1\25\5\0\2\25\3\0"+
    "\5\25\1\202\22\25\23\0\1\25\5\0\2\25\3\0"+
    "\2\25\1\220\25\25\23\0\1\25\5\0\2\25\3\0"+
    "\7\25\1\202\20\25\23\0\1\25\5\0\2\25\3\0"+
    "\4\25\1\210\23\25\23\0\1\25\5\0\2\25\3\0"+
    "\10\25\1\221\17\25\41\0\1\222\47\0\1\25\5\0"+
    "\2\25\3\0\22\25\1\200\5\25\23\0\1\25\5\0"+
    "\2\25\3\0\4\25\1\223\23\25\23\0\1\25\5\0"+
    "\2\25\3\0\12\25\1\224\15\25\23\0\1\25\5\0"+
    "\2\25\3\0\17\25\1\202\10\25\23\0\1\25\5\0"+
    "\2\25\3\0\4\25\1\220\23\25\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6480];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\1\11\2\1\1\11\2\1\1\11"+
    "\3\1\2\11\4\1\1\11\21\1\1\11\1\1\2\11"+
    "\1\0\1\1\1\11\1\0\3\11\3\0\1\1\1\0"+
    "\27\1\1\11\2\0\34\1\1\0\22\1\1\0\13\1"+
    "\1\0\4\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
private Structure data = new Structure();
private Structure errors = new Structure();

Structure getData() {
    return this.data;
}

Structure getErrors() {
    return this.errors;
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    System.out.println(data.toString());
    System.out.println(errors.toString());
    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { data.addData(yytext(), Types.ERROR, yyline);
            }
            // fall through
          case 29: break;
          case 2:
            { /* DO NOTHING */
            }
            // fall through
          case 30: break;
          case 3:
            { data.addData(yytext(), Types.OPERATOR_BOOLEAN, yyline);
            }
            // fall through
          case 31: break;
          case 4:
            { data.addData(yytext(), Types.OPERATOR_REMAINDER, yyline);
            }
            // fall through
          case 32: break;
          case 5:
            { data.addData(yytext(), Types.OPERATOR_BINARY, yyline);
            }
            // fall through
          case 33: break;
          case 6:
            { data.addData(yytext(), Types.OPERATOR_PARENTHESIS, yyline);
            }
            // fall through
          case 34: break;
          case 7:
            { data.addData(yytext(), Types.OPERATOR_MULTIPLY, yyline);
            }
            // fall through
          case 35: break;
          case 8:
            { data.addData(yytext(), Types.OPERATOR_ADD, yyline);
            }
            // fall through
          case 36: break;
          case 9:
            { data.addData(yytext(), Types.OPERATOR_SEPARATE, yyline);
            }
            // fall through
          case 37: break;
          case 10:
            { data.addData(yytext(), Types.OPERATOR_SUBTRACT, yyline);
            }
            // fall through
          case 38: break;
          case 11:
            { data.addData(yytext(), Types.OPERATOR_DIVIDE, yyline);
            }
            // fall through
          case 39: break;
          case 12:
            { data.addData(yytext(), Types.OPERATOR_END_LINE, yyline);
            }
            // fall through
          case 40: break;
          case 13:
            { data.addData(yytext(), Types.OPERATOR_ASSIGNMENT, yyline);
            }
            // fall through
          case 41: break;
          case 14:
            { data.addData(yytext(), Types.IDENTIFIER, yyline);
            }
            // fall through
          case 42: break;
          case 15:
            { data.addData(yytext(), Types.OPERATOR_SQ_BRACKET, yyline);
            }
            // fall through
          case 43: break;
          case 16:
            { data.addData(yytext(), Types.OPERATOR_BRACKET, yyline);
            }
            // fall through
          case 44: break;
          case 17:
            { System.out.print(yytext());
            }
            // fall through
          case 45: break;
          case 18:
            { data.addData(yytext(), Types.LITERAL_STRING, yyline);
            }
            // fall through
          case 46: break;
          case 19:
            { data.addData(yytext(), Types.OPERATOR_INC, yyline);
            }
            // fall through
          case 47: break;
          case 20:
            { data.addData(yytext(), Types.OPERATOR_DEC, yyline);
            }
            // fall through
          case 48: break;
          case 21:
            { data.addData(yytext(), Types.OPERATOR_MEMORY, yyline);
            }
            // fall through
          case 49: break;
          case 22:
            { data.addData(yytext(), Types.RESERVED_LOOP, yyline);
            }
            // fall through
          case 50: break;
          case 23:
            { data.addData(yytext(), Types.RESERVED_CONDITION, yyline);
            }
            // fall through
          case 51: break;
          case 24:
            { data.addData(yytext(), Types.LITERAL_CHARACTER, yyline);
            }
            // fall through
          case 52: break;
          case 25:
            { data.addData(yytext(), Types.RESERVED_DATA_TYPE, yyline);
            }
            // fall through
          case 53: break;
          case 26:
            { data.addData(yytext(), Types.RESERVED_ENUM, yyline);
            }
            // fall through
          case 54: break;
          case 27:
            { data.addData(yytext(), Types.RESERVED_WORDS, yyline);
            }
            // fall through
          case 55: break;
          case 28:
            { data.addData(yytext(), Types.RESERVED_MODIFIER, yyline);
            }
            // fall through
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Scanner(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
