
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 18 22:25:51 CST 2021
//----------------------------------------------------

package Scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESERVED_DATA_TYPE = 14;
  public static final int OPERATOR_SEPARATE = 33;
  public static final int OPERATOR_SQ_BRACKET = 37;
  public static final int OPERATOR_BRACKET = 30;
  public static final int OPERATOR_END_LINE = 31;
  public static final int LITERAL_EXPONENTIAL_FLOAT = 21;
  public static final int OPERATOR_BINARY = 28;
  public static final int OPERATOR_DEC = 23;
  public static final int OPERATOR_NEGATIVE = 32;
  public static final int COMMENTS_ERROR = 5;
  public static final int RESERVED_WORDS = 11;
  public static final int OPERATOR_REMAINDER = 35;
  public static final int LITERAL_DECIMAL = 19;
  public static final int OPERATOR_DIVIDE = 27;
  public static final int RESERVED_CONDITION = 13;
  public static final int OPERATOR_MULTIPLY = 34;
  public static final int LITERAL_CHARACTER = 20;
  public static final int OPERATOR_CONTINUE_LINE = 39;
  public static final int STRING_ERROR = 3;
  public static final int FLOAT_MANY_DOTS_ERROR = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RESERVED_LOOP = 9;
  public static final int CHARACTER_ERROR = 6;
  public static final int OPERATOR_BOOLEAN = 29;
  public static final int LITERAL_FLOAT = 16;
  public static final int LITERAL_HEXA = 15;
  public static final int LITERAL_STRING = 18;
  public static final int IDENTIFIER_ERROR = 7;
  public static final int OPERATOR_INC = 22;
  public static final int RESERVED_MODIFIER = 12;
  public static final int OPERATOR_DOT = 25;
  public static final int UNKNOWN_ERROR = 4;
  public static final int RESERVED_ENUM = 10;
  public static final int OPERATOR_ADD = 24;
  public static final int OPERATOR_ASSIGNMENT = 36;
  public static final int OPERATOR_MEMORY = 26;
  public static final int LITERAL_OCTAL = 17;
  public static final int OPERATOR_PARENTHESIS = 38;
  public static final int IDENTIFIER = 2;
}

